### ISSUE TITLE
Bump vue to vue 3.0.4

### ISSUE THREAD

**Issue by redsuperbat** [Tahul/vue-use-sound#6]
Please bump vue to the latest version. Right now it does not wanna install in my vue 3 project!

**Comment by Tahul** [comment]
Hello @redsuperbat ;

Could you provide the log message from your package manager so I can take a look at what's wrong with using the package with Vue 3.0.4 ?

As you can see in the repository, the "demo" folder is actually running Vue 3.0.4 and vue-use-sound without any problems.

The peerDependency parameter is allowing >=3.0.0-rc0 (first Vue 3 release), so it should actually accept every version of Vue 3.

Thank you for your issue anyway, I hope we can find a fix to your problem.

**Comment by redsuperbat** [comment]
Alright cool. I did not see that. Here are the logs trying to use npm to install the package:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: netterberg_co@0.1.1
npm ERR! Found: vue@3.0.4
npm ERR! node_modules/vue
npm ERR!   vue@"^3.0.3" from the root project
npm ERR!   peer vue@"^2.0.0 || >=3.0.0-rc.0" from vue-use-sound@1.0.2
npm ERR!   node_modules/vue-use-sound
npm ERR!     vue-use-sound@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 3" from @vue/composition-api@1.0.0-beta.22
npm ERR! node_modules/@vue/composition-api
npm ERR!   peer @vue/composition-api@"^1.0.0-beta.1" from vue-use-sound@1.0.2
npm ERR!   node_modules/vue-use-sound
npm ERR!     vue-use-sound@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/max/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/max/.npm/_logs/2020-12-21T12_13_15_677Z-debug.log

**Comment by Tahul** [comment]
You should maybe try following the error output and try --force & --legacy-peer-deps.

I'm using this package on at least 2 Vue 3 projects, and it works seamlessly.

I would be glad to help you out if you could provide a little bit more details about your project.

Thanks you @redsuperbat

**Comment by Tahul** [comment]
(Also, I can advise you to try removing .node_modules and running npm install again.)

**Comment by redsuperbat** [comment]
Hey! 

Decided to write my own hook instead! My usecase was limited anyway so it was a better solution ☺️ Might revisit this later if the need for the package arises but for now I'll close the issue!
