### ISSUE TITLE
File-Loader

### ISSUE THREAD

**Issue by ericwaetke** [Tahul/vue-use-sound#7]
This isn't strictly speaking an issue with the package, I'm just really struggling here, and  I could imagine others too!

I'm currently not as experienced as I probably should be with anything regarding webpack/babel etc. Therefore, I have no Idea how to fix following issue

```
Module parse failed: Unexpected token (34:28)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     };
|     watch(() => [url], () => {
>         if (HowlConstructor?.value && sound?.value) {
|             sound.value = new HowlConstructor.value({
|                 src: [url],

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=js 3:0-37 14:12-20
 @ ./src/App.vue?vue&type=script&lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.178.20:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

I've tried installing the webpack file-loader, but that failed since I don't think I use Webpack but Babel in Vue 3. (Also my first Vue 3 project, I've only worked in Vue 2 before)

I've tried `babel-plugin-file-loader` with this configuration (basically the standard one with mp3 added as extensions)

```
"plugins": [
    [
      "file-loader",
      {
        "name": "[hash].[ext]",
        "extensions": ["png", "jpg", "jpeg", "gif", "svg", "mp3"],
        "publicPath": "/public",
        "outputPath": "/public",
        "context": "/src",
        "limit": 0
      }
    ]
  ]
```

But the error still occurs. I'm honestly just really lost with this whole loader thing, if you could include an example loader-config or something like that when you have time, that'd be awesome!

**Comment by Thaiten** [comment]
I've deleted all custom installed file-loaders and tried again. Then, I've downloaded your demo folder and tried to run that. Both times, I got this error `TypeError: (0 , _schemaUtils.validate) is not a function`

Only thing I've changed is that I tried to serve w/ the vue-cli. Could that be the issue?

**Comment by Tahul** [comment]
Hello @ericwaetke ; I was quite busy during the winter break, I'll be taking a look at your issue right now.

**Comment by Tahul** [comment]
Could you explain me a little bit more about your project setup ?

I don't see why you would use Webpack, as since Vue 3 we have the Vite tool that helps with creating new projects.

You are not supposed to be using vue-cli when you create a Vue 3 project.

I recommend you to take a look here: https://github.com/vitejs/vite

I just created a dummy Vue 3 project using Vite, and added vue-use-sound to try if it works, and actually it does work perfectly from my side.

If you have any other question, please ask, I'll be glad to help you with your project.

**Comment by ericwaetke** [comment]
Using vite does indeed work!
I wasn't aware that one shouldn't use vue-cli with Vue 3 projects, thanks for the info!

**Comment by Tahul** [comment]
You're welcome @ericwaetke.

If there's anything I can help you with, don't mind asking.

I'll be closing this issue for now, as your problem seem to be resolved.

Have fun using vue-use-sound. :)
