### ISSUE TITLE
Reactive Volume

### ISSUE THREAD

**Issue by ericwaetke** [Tahul/vue-use-sound#8]
Reactive Playback-Rate works perfectly fine.

The reactive volume should work too, since it uses the same watcher and is updated/set the same way as the playbackRate, I do however get following error

`Uncaught (in promise) TypeError: AudioParam.setValueAtTime: Argument 1 is not a finite floating-point value.`

The error occurs right on load, I can't even update the volume ref.

```
const volume = ref(0.5);
const [press] = useSound(buttonPress, {volume})
```

I don't see what's the difference between the playbackRate value and the volume value, and I haven't looked into this further yet, so I don't know what's causing this error.

**Comment by Tahul** [comment]
Hello @ericwaetke ;

You're right, volume should be reactive too.

I'll be taking a look at the code soon, thank you a lot for your issue report.

**Comment by Tahul** [comment]
Hey @ericwaetke ; I got it.

I was thinking I could use watch() to look watch for a composable parameter.

Actually, I have to proxy the function parameters on a reactive object, and use this reactive object afterwards.

I also have to update the function typings accordingly.

I'll be fixing that now, thank you for your issue.

**Comment by Tahul** [comment]
Hey @ericwaetke ;

I just fixed this issue in the latest version, 1.1.0.

Could you try it and tell me if it's working better from your side ? 😄

👋

**Comment by ericwaetke** [comment]
Awesome!
The error is definitely gone; it currently [does not work when I pass the volume as a prop](https://i.imgur.com/xC4r3Dr.png). I'll look into that tomorrow, I'm not quite sure if refs just work with props like that.

**Comment by ericwaetke** [comment]
Okay, this is odd. I've stripped everything down as much as I could, and as stated before I do not get any issues.

I may be overlooking something though.

```
setup(props){
  const volume = ref(0.5);
  const [press] = useSound(buttonPress, {volume})
  
  function changeVolume(){
	  switch (volume.value) {
		  case 0:
			  volume.value = 0.5;
			  break;
		  case 0.5:
			  volume.value = 1;
			  break;
		  case 1:
			  volume.value = 0;
			  break;
		  default:
			  volume.value = 0.5;
			  break;
	  }
	  console.log(volume.value);
	  press();
  }
  return{
	  changeVolume
  }
}
```

The value of the ref changes, so the volume **should** in theory change too. I'll set up a new project now to see if there is a bug hidden in this one somewhere and edit this once I've got an update.

**Comment by Tahul** [comment]
Hello @ericwaetke ;

I'll be writing an example for sound updates on the vue-use-sound.netlify.app today.

I hope it'll fix your problems, when I tried on a local example yesterday it seemed to work.

See you soon for that update, and sorry again for the time these errors made you lost.

**Comment by Tahul** [comment]
Hey @ericwaetke ;

I just added the example I told you about on my demo page.

https://vue-use-sound.netlify.app

It's at the very bottom of the page, I hope you can fix your problem with my latest updates.

Don't forget to update the vue-use-sound package, as I pushed 2 new versions today.

Can't wait to see what you'll build with it. 🤗

**Comment by ericwaetke** [comment]
Ah yes, the 1.1.1 fixes the problem! Awesome and thanks for the quick fix!
